version: "3.8"

#
# This docker-compose file allows you set up a local roshambr alongside the required prometheus
# instance. This file may also be used during the integration testing phase and sets up all required services used for
# testing.
#
# services:
#
#          roshambr - core spring boot backend for the roshambr service
#          prometheus - the prometheus instance used for metrics
#

services:
  roshambr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8050:8050
      - 8000:8000
    networks:
      - roshambr
    depends_on:
      prometheus:
        condition: service_started
    #environment: TODO

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - roshambr

volumes:
  prometheus_data: {}

networks:
  roshambr:
    driver: bridge